version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: pissboy
    environment:
      POSTGRES_USER: piss
      POSTGRES_PASSWORD: boyboy
      POSTGRES_DB: pissboy-db
    ports:
      - "5443:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
